# Generated by Django 4.2.1 on 2023-06-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=200)),
            ],
        ),
    ]
