# Generated by Django 3.2.16 on 2023-06-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IngeniousPrediction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
