# Generated by Django 3.2.16 on 2023-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngeniousPrediction', '0002_delete_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('URL', models.CharField(max_length=150, null=True)),
                ('data', models.FileField(upload_to='IngeniousPrediction/data/')),
            ],
        ),
    ]
